services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3003 -b '0.0.0.0'"
    image: graphql_web
    container_name: graphql_web
    volumes:
      - .:/rails-on-graphql/
    ports:
      - "3003:3003"
    networks:
    - policy-service
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      # - RABBITMQ_USERNAME=user
      # - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOSTNAME=rabbitmq
    networks:
      - policy-service
networks:
  default:
  policy-service:
    external: true

